### ISSUE TITLE
CPCollectionViewKit cant find

### ISSUE THREAD

**Issue by hamzauzumcu** [ParsifalC/CPCollectionViewKit#2]
CPCollectionViewKit deleted on https://cocoapods.org

How can i download this?

**Comment by ParsifalC** [comment]
You can import it manually.
[Click me to Download](https://github.com/ParsifalC/CPCollectionViewKit/archive/master.zip).

**Comment by hamzauzumcu** [comment]
I did but you should publish on cocoapods.

**Comment by ParsifalC** [comment]
Yeah.You are right.Would you like to send me a pull request?
